### ISSUE TITLE
What does twist define in constant_velocity_cartesian_plan() & cartesian_path_plan() in planning.py

### ISSUE THREAD

**Issue by lakshmip001** [crigroup/raveutils#11]
In the test_planning.py the following is defined:
```
  def test_plan_constant_velocity_twist(self):
    np.random.seed(123)
    env = self.env
    robot = self.robot
    velocity = 0.002
    distances = [0.01, 0.02, 0.1, 0.5, 1.]
    for dist in distances:
      while True:
        q = ru.kinematics.random_joint_values(robot)
        with env:
          robot.SetActiveDOFValues(q)
        if not env.CheckCollision(robot):
          break
      twist = np.random.rand(6)*dist
      traj = ru.planning.plan_constant_velocity_twist(robot, twist, velocity)
    # Superpass velocity limits
    np.random.seed(123)
    velocity = 0.02
    twist = np.random.rand(6)*0.02
    traj = ru.planning.plan_constant_velocity_twist(robot, twist, velocity)
```
while distances is a 5d and then twist is obtained from above. Does twist represent linear velocity and angular velocity or is it a cartesian point it should reach to (i.e the end point to plan in cartesian space(pose vector). If it is a pose vector what is the representation pose.linear and pose.rotation(quartenion,or rpy or transform).

**Comment by fsuarez6** [comment]
The twist is linear and angular velocity:

![CodeCogsEqn](https://user-images.githubusercontent.com/4430326/55695138-c5112d00-59e9-11e9-85d7-5ab1ac661a91.gif)

`test_plan_constant_velocity_twist` is generating twists, randomly, with different _magnitudes_: [0.01, 0.02, 0.1, 0.5, 1.].

The units are:
- Linear velocity: m/s^2
- Angular velocity: rad/s^2

**Comment by lakshmip001** [comment]
> The twist is linear and angular velocity:
> 
> ![CodeCogsEqn](https://user-images.githubusercontent.com/4430326/55695138-c5112d00-59e9-11e9-85d7-5ab1ac661a91.gif)
> 
> `test_plan_constant_velocity_twist` is generating twists, randomly, with different _magnitudes_: [0.01, 0.02, 0.1, 0.5, 1.].
> 
> The units are:
> 
>     * Linear velocity: m/s^2
> 
>     * Angular velocity: rad/s^2

Thanks . I would like to know if I can use this for moving it to a specific pose in cartesian space?

**Comment by fsuarez6** [comment]
Yes, you could. Check this test/example: https://github.com/crigroup/raveutils/blob/master/tests/test_planning.py#L85

**Comment by lakshmip001** [comment]
I tried the example but it gives an error  

'NoneType' object has no attribute 'GetConfigurationSpecification'

configurationspecification() is set inside the ru.planning.plan_constant_velocity_twist(robot, twist, velocity)

but I get the below error. I did using IPython and the error is as shown in the figure:
![Screenshot from 2019-04-08 12-09-52](https://user-images.githubusercontent.com/30099654/55698253-95692180-59f7-11e9-90d5-c6b27c2b249e.png)
How to solve this error?

**Comment by lakshmip001** [comment]
I am able get a ros trajectory as shown below:
```
<trajectory:GenericTrajectory>
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
joint_names: []
points: 
  - 
    positions: [-1.0599999999999998, -1.5, -1.81, -2.98, -1.13, -3.14]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 0
      nsecs:         0
  - 
    positions: [-1.0164553535006118, -1.5094028138118336, -1.794036731907412, -3.005938413761572, -1.1040675774743887, -3.1141153309685916]
    velocities: [0.12013277333536547, -0.02594087198267903, 0.044040124828789134, -0.0715599696312069, 0.07154344076142538, 0.07141169644481644]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 0
      nsecs: 362471000
  - 
    positions: [-0.9744004752308313, -1.5210204447213551, -1.7761417015993233, -3.0317290186404255, -1.0800918229824894, -3.0870056883553434]
    velocities: [0.11602273907312453, -0.03205120107628122, 0.04936955039608138, -0.07115218836687114, 0.0661453039918499, 0.07479120427136436]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 0
      nsecs: 724942000
  - 
    positions: [-0.9339667466041329, -1.5347554690510685, -1.7563345386550353, -3.057414577239583, -1.0582255755339496, -3.0587906961756484]
    velocities: [0.11155024432872725, -0.03789275369545996, 0.05464482106741156, -0.07086238234195308, 0.06032550863554078, 0.07784068841229505]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 1
      nsecs:  87413000
  - 
    positions: [-0.895252288191503, -1.5504967305520203, -1.734637263585523, -3.0830301405354783, -1.038582594004921, -3.029607411892219]
    velocities: [0.1068070504912993, -0.04342764385360472, 0.059859340641505124, -0.07066927640179205, 0.05419187058254578, 0.08051205275146789]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 1
      nsecs: 449884000
  - 
    positions: [-0.8583227185027682, -1.5681235907821178, -1.7110731556249865, -3.1086016446090534, -1.0212378570086147, -2.9996071320513344]
    velocities: [0.10188282559261785, -0.048629711683759735, 0.06500963650062, -0.07054772399537917, 0.047851378427611106, 0.08276601391569853]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 1
      nsecs: 812355000
  - 
    positions: [-0.8232132560535064, -1.587510357981914, -1.6856653705818587, -3.134145657396779, -1.0062294253986936, -2.968951443208213]
    velocities: [0.09686143839525638, -0.05348501588482022, 0.07009604915687198, -0.07047187989794856, 0.04140588241402645, 0.08457418340236118]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 2
      nsecs: 174826000
  - 
    positions: [-0.7899318095276529, -1.6085306455890123, -1.6584353501810027, -3.1596702519474476, -0.9935615334034, -2.937807748026287]
    velocities: [0.09181823239326613, -0.057991639605644955, 0.0751233074949735, -0.07041830806171767, 0.03494870483628572, 0.08592051549134999]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 2
      nsecs: 537297000
  - 
    positions: [-0.7584626837258246, -1.6310614516158977, -1.6294010695481285, -3.1851768603101305, -0.9832085384238781, -2.9063445513663515]
    velocities: [0.08681832695705208, -0.062158920351528216, 0.08010097531216587, -0.07036868702174937, 0.02856227112176769, 0.08680196939495607]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 2
      nsecs: 899768001
  - 
    positions: [-0.7287705574766854, -1.6549868057200996, -1.598575165703507, -3.2106628736819047, -0.975119368537851, -2.8747268128976518]
    velocities: [0.0819158670304752, -0.0660062573158983, 0.08504377959471272, -0.07031186870828067, 0.022316736740600678, 0.08722832573438175]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 3
      nsecs: 262239001
  - 
    positions: [-0.700804448021881, -1.6802008938932291, -1.5659629765422134, -3.2361247113295177, -0.9692221476321317, -2.8431116583441254]
    velocities: [0.07715406044812555, -0.06956167021365058, 0.08997185747136116, -0.07024517171968797, 0.01626949715587428, 0.08722119712223916]
    accelerations: []
    effort: []
    time_from_start: 
      secs: 3
      nsecs: 624710001
[-0.700804448021881, -1.6802008938932291, -1.5659629765422134, -3.2361247113295177, -0.9692221476321317, -2.8431116583441254]
[-0.00421558  0.20058173 -0.00027156]
```

when I just open robot only in openrave the robot moves to the position. But when linked with real robot , robot doesn't move at all neither in openrave nor on the real robot.
